added more flexible binning
LSSTDESC/TJPCov pull request #109
Opened 2024-06-05 15:57 UTC by fjaviersanchez

Some of us have discussed online the possibility of adding more flexible binning for the covariance calculation using TJPCov, for example, reading bandpower windows. Here's a first draft implementation for that.

2024-06-05 15:57 UTC, fjaviersanchez commented
@carlosggarcia, please feel free to assign someone else as a reviewer!!

2024-07-07 12:28 UTC, carlosggarcia requested changes
Seems to be some problem with the unit tests, I think it has to do with GitHub because they passed in my laptop. For some reason, I cannot rerun the actions, so cannot check.

Just a minor comment.

2024-07-07 12:28 UTC, carlosggarcia commented on tjpcov/covariance_gaussian_fsky.py
> +        out = super().get_binning_info()
Why not `self.get_binning_info()`?

2024-07-22 17:52 UTC, fjaviersanchez commented on tjpcov/covariance_gaussian_fsky.py
> +        out = super().get_binning_info()
Updated!

2024-07-23 10:44 UTC, carlosggarcia approved these changes
LGTM!

2024-07-23 19:54 UTC, fjaviersanchez commented
thanks! I think that the unit tests are broken. I can open a separate PR to try to fix them and then rebase because it doesn't allow me to merge as is :(

2024-07-24 14:17 UTC, carlosggarcia commented
Actually it looks like that! Pinging @damonge. I think we can merge this since the tests passed in my laptop

2024-07-24 14:18 UTC, merged