Quick fix to skip mass-richness relation
LSSTDESC/TJPCov pull request #79
Opened 2023-03-03 19:38 UTC by m-aguena

This solves only part of issue #75

2023-04-05 14:52 UTC, mattkwiecien commented
@m-aguena Did you mean to publish this PR to be ready for review or are you still working on it?

2023-04-05 15:02 UTC, m-aguena commented
It is still in progress. I have to update the unittests

2023-05-05 13:39 UTC, m-aguena commented
@mattkwiecien I tried to run the unit tests but got a sacc related error:
```
===================================================================================================== ERRORS ======================================================================================================
______________________________________________________________________________________ ERROR at setup of test_load_from_sacc ______________________________________________________________________________________

    @pytest.fixture
    def mock_sacc():
        # Using values from
        # https://github.com/nrussofer/Cosmological-Covariance-matrices
        # /blob/master/Full%20covariance%20N_N%20part%20vfinal.ipynb
        # As reference.
        s = sacc.Sacc()
        s.metadata["nbins_cluster_redshift"] = 18
        s.metadata["nbins_cluster_richness"] = 3
        s.metadata["min_mass"] = 1e13
    
        # This isnt how tracers actually look, but sort of
        # hacks the class to work without building
        # an entire sacc file for this test.
>       s.add_tracer(
            "misc",
            "clusters_0_0",
            metadata={
                "Mproxy_name": "richness",
                "Mproxy_min": 10,
                "Mproxy_max": 100,
                "z_name": "redshift",
                "z_min": 0.3,
                "z_max": 1.2,
            },
        )

tests/test_covariance_clusters.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../sacc/sacc/sacc.py:138: in add_tracer
    tracer = BaseTracer.make(tracer_type, name,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'sacc.tracers.BaseTracer'>, tracer_type = 'misc', name = 'clusters_0_0', args = (), kwargs = {'metadata': {'Mproxy_max': 100, 'Mproxy_min': 10, 'Mproxy_name': 'richness', 'z_max': 1.2, ...}}

    @classmethod
    def make(cls, tracer_type, name, *args, **kwargs):
        """
        Select a Tracer subclass based on tracer_type
        and instantiate in instance of it with the remaining
        arguments.
    
        Parameters
        ----------
        tracer_type: str
            Must correspond to the tracer_type of a subclass
    
        name: str
            The name for this specific tracer.
    
        Returns
        -------
        instance: Tracer object
            An instance of a Tracer subclass
        """
>       subclass = cls._tracer_classes[tracer_type]
E       KeyError: 'misc'

../sacc/sacc/tracers.py:75: KeyError

```
I don't know the source of it. Could this be related to a latest sacc version?

2023-05-05 13:41 UTC, joezuntz commented
Sorry, this is indeed caused my the latest sacc version which means you have to write "Misc" instead of "misc". I hadn't appreciated this would happen, apologies. I have a PR now in sacc to fix it.

2023-05-05 14:15 UTC, m-aguena commented
> Sorry, this is indeed caused my the latest sacc version which means you have to write "Misc" instead of "misc". I hadn't appreciated this would happen, apologies. I have a PR now in sacc to fix it.

Thanks @joezuntz !

2023-05-05 17:59 UTC, mattkwiecien commented
@m-aguena I would recommend pulling latest master and rebasing (or merging into) your branch, we made some changes to the tests since you've branched off master.  

@joezuntz thank you!

2023-07-18 18:12 UTC, mattkwiecien requested changes

2023-07-18 18:34 UTC, m-aguena commented on tjpcov/covariance_clusters.py
> +            m_integ_upper = np.log(10) * self.richness_bins[richness_i + 1]
@mattkwiecien in this example, the else statement is not needed for functional purposes. Do you think it is good to keep it for would user readability?

2023-07-18 22:54 UTC, mattkwiecien approved these changes

2023-07-19 16:47 UTC, merged